### ISSUE TITLE
Don't error out if an alert is missing a frame

### ISSUE THREAD

**Issue by apockill** [aotuai/brainframe-qt#165]
Alerts can be missing a frame in two scenarios:

1) When a user clears the `volumes/storage` directory of old pictures
2) When the JournalReaper clears old alert frames
3) In the https://github.com/aotuai/brainframe/pull/1483 PR where potentially the `journal` is unable to request a frame from the `core`, and thus saves an alert table without an AlertFrame. 

Currently, in any of these cases, this traceback shows up:
```
Traceback (most recent call last):
  File "/home/alex/workspace/brainframe-qt/brainframe_qt/ui/main_window/video_expanded_view/alert_log/alert_log_entry/alert_log_entry.py", line 162, in display_alert_info
    AlertEntryPopup.show_alert(self.alert_text, self.alert.id, self)
  File "/home/alex/workspace/brainframe-qt/brainframe_qt/ui/dialogs/alert_entry_popup/alert_entry_popup.py", line 28, in show_alert
    dialog = cls(alert_message, alert_id, parent=parent)
  File "/home/alex/workspace/brainframe-qt/brainframe_qt/ui/dialogs/alert_entry_popup/alert_entry_popup.py", line 21, in __init__
    self.alert_frame_label.setPixmap(self.get_frame(alert_id))
  File "/home/alex/workspace/brainframe-qt/brainframe_qt/ui/dialogs/alert_entry_popup/alert_entry_popup.py", line 36, in get_frame
    height, width, channels = frame.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

Relevant source code: https://github.com/aotuai/brainframe-qt/blob/d2655379fb34cc95b91b9c7832ccc6af96f2bf33/brainframe_qt/ui/dialogs/alert_entry_popup/alert_entry_popup.py#L32

To fix this, we simply have to check if `api.get_alert_frame(alert_id)` returned None, and replace `frame` with a nice image describing the nature of the problem (no image was found for this alert)

**Comment by apockill** [comment]
@velovix Could you whip up an image that would go here, when an alerts frame isn't found? 
![image](https://user-images.githubusercontent.com/1740412/122147944-a7804f00-ce0e-11eb-8131-f5947e49442b.png)

**Comment by velovix** [comment]
I already made one called `no_image_available.png` and it looks like it's used in code. Maybe this feature is broken.

**Comment by apockill** [comment]
Looks like it got used for the alerts activity, but not for when you click on an alert
