### ISSUE TITLE
BrainFrame Client "Select video file" window shows empty for a mounted harddrive

### ISSUE THREAD

**Issue by stephenli2000** [aotuai/brainframe-qt#208]
BrainFrame Client "Select video file" window only shows "WDC_SSD" under /mnt. Then if I manually type in HDD, BrainFrame Client will show both. Same thing for every folder and file inside the WDC_SSD,

stephen@AOTU-001:~/data/dilili_videos$ ls -l /mnt
total 8
drwxr-xr-x 7 root    root    4096 Oct  6 12:06 HDD
drwx------ 6 stephen stephen 4096 Oct  2 22:35 WDC_SSD
stephen@AOTU-001:~/data/dilili_videos$ ls -l /mnt/HDD
total 12
drwxr-xr-x  9 stephen root 4096 Oct  8 17:05 data
drwxr-xr-x 58 root    root 4096 Oct  1 21:37 data_zhao
drwx--x--- 13 root    root 4096 Oct 13 10:16 docker
stephen@AOTU-001:~/data/dilili_videos$ ls -l /mnt/HDD/data
total 32
drwxrwxr-x 6 stephen stephen 4096 Oct 12 15:39 dilili_videos

stephen@AOTU-001:~/data/dilili_videos$ ls -l /mnt/HDD/data/dilili_videos/dilili_coworkers.mp4
-rw-rw-r-- 1 stephen stephen 56460949 Oct  9 12:13 /mnt/HDD/data/dilili_videos/dilili_coworkers.mp4

Finally if I type in everything for the dilili_coworders.mp4, it gives me below error,

Traceback (most recent call last): File "/snap/brainframe-client/109/usr/local/lib/python3.6/site-packages/brainframe_qt/ui/resources/qt_async_worker.py", line 47, in run self.data = self.func(*self.f_args, **self.f_kwargs) File "/snap/brainframe-client/109/usr/local/lib/python3.6/site-packages/brainframe_qt/ui/main_window/activities/stream_configuration/stream_configuration.py", line 282, in upload with reader: File "/snap/brainframe-client/109/usr/local/lib/python3.6/site-packages/brainframe_qt/ui/resources/progress_file_reader.py", line 59, in __enter__ self._file = self.filepath.open("rb") File "/snap/brainframe-client/109/usr/lib/python3.6/pathlib.py", line 1183, in open opener=self._opener) File "/snap/brainframe-client/109/usr/lib/python3.6/pathlib.py", line 1037, in _opener return self._accessor.open(self, flags, mode) File "/snap/brainframe-client/109/usr/lib/python3.6/pathlib.py", line 387, in wrapped return strfunc(str(pathobj), *args)PermissionError: [Errno 13] Permission denied: '/home/stephen/data/dilili_videos/dilili_coworkers.mp4'

The "Uploading /mnt/HDD/data/dilili_videos/dilili_coworkers.mp4..." window will stay there forever.

**Comment by apockill** [comment]
This looks like a snap sandboxing issue. Snap restricts the paths that the program can access, as part of the sandboxing it automatically does.

**Comment by velovix** [comment]
I think the fix here would be to add the `removable-media` interface to the Snap. That interface does not auto-connect, meaning that the BrainFrame Client will not get access to stuff under `/mnt` automatically. However, it would let the user add that permission in the Ubuntu Store or run the following command: 

```bash
sudo snap connect brainframe-client:removable-media
```
